config/routes.rb
Rails.application.routes.draw do

  resources :projects

  root 'welcome#index'

end

app/models/employee.rb
class Employee
  include Mongoid::Document
  field :name, type: String
end

app/models/project.rb
class Project
  include Mongoid::Document
  include Mongoid::Timestamps
  field :name                 , type: String
  field :region_primary       , type: String
  field :vendor               , type: String
  field :client               , type: String
  field :total_num_of_builds  , type: Integer
  field :last_build_date      , type: DateTime
  
  embeds_many :developers, class_name: "Employee"
  embeds_many :product_owners, class_name: "Employee"
  embeds_one :qualityMetric
  
  
end

app/models/quality_metric.rb
class QualityMetric
  include Mongoid::Document
  field :code_coverage                    , type: Int
  field :build_success_rate               , type: Int
  field :critical_defect_resolution_rate  , type: Int
  field :release_frequency_per_month      , type: Int
  field :high_code_quality_violations     , type: Int
  field :code_complexity                  , type: Int
  field :velocity                         , type: Int
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      
      params.require(:project).permit(:name, :vendor, :client)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Yudh</title>
  <script src="//code.jquery.com/jquery-1.11.0.min.js"></script>
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">

  <!-- Optional theme -->
  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap-theme.min.css">

  <!-- Latest compiled and minified JavaScript -->
  <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">

<%= yield %>

</div>
</body>
</html>

app/views/projects/_form.html.erb
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<!-- Refer http://bootsnipp.com/snippets/featured/input-validation-colorful-input-groups for styling-->
    
    <div class="row">
        <div class="col-sm-offset-4 col-sm-4">
            <%= form_for(@project) do |f| %>
			
							<div class="form-group">
								<%= f.label :name %>
								<div class="input-group">
									<%= f.text_field :name , class: "form-control", required: true %>
									<span class="input-group-addon danger"><span class="glyphicon glyphicon-remove"></span></span>
								</div>
							</div>
							
							<div class="form-group">
								<%= f.label :vendor %>
								<div class="input-group">
									<%= f.text_field :vendor , class: "form-control", required: true %>
									<span class="input-group-addon danger"><span class="glyphicon glyphicon-remove"></span></span>
								</div>
							</div>
							
							<div class="form-group">
								<%= f.label :client %>
								<div class="input-group">
									<%= f.text_field :client , class: "form-control", required: true %>
									<span class="input-group-addon danger"><span class="glyphicon glyphicon-remove"></span></span>
								</div>
							</div>
							
							<%= f.submit class: "btn btn-default"%>
				
            <% end %>
        </div>
    </div>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<!-- Refer http://bootsnipp.com/snippets/featured/responsive-list-groups-for-ratings for styling-->

<div class="row">
	<div class="well">
		<h1 class="text-center">Listing projects</h1>
		<div class="list-group">
		<% @projects.each_with_index do |project, index| %>
			<a href="#" class="list-group-item <%= index%2==0 ? 'active' : ''%>">
			    <div class="media col-md-3">
			        <figure class="pull-left">
			            <img class="media-object img-rounded img-responsive"  src="http://placehold.it/350x250" alt="placehold.it/350x250" >
			        </figure>
			    </div>
			    <div class="col-md-6">
			        <h4 class="list-group-item-heading"> <%= project.name %></h4>
			        <p class="list-group-item-text"> Qui diam libris ei, vidisse incorrupte at mel. His euismod salutandi dissentiunt eu. Habeo offendit ea mea. Nostro blandit sea ea, viris timeam molestiae an has. At nisl platonem eum. 
			            Vel et nonumy gubergren, ad has tota facilis probatus. Ea legere legimus tibique cum, sale tantas vim ea, eu vivendo expetendis vim. Voluptua vituperatoribus et mel, ius no elitr deserunt mediocrem. Mea facilisi torquatos ad.
			        </p>
			    </div>
			    <div class="col-md-3 text-center">
			        <h2> 14240 <small> points </small></h2>
					<%= button_to "See Details", project_path(project), :method => "get", :class => "btn btn-default btn-lg btn-block" %>

			        <div class="stars">
			            <span class="glyphicon glyphicon-star"></span>
			            <span class="glyphicon glyphicon-star"></span>
			            <span class="glyphicon glyphicon-star"></span>
			            <span class="glyphicon glyphicon-star"></span>
			            <span class="glyphicon glyphicon-star-empty"></span>
			        </div>
			        <p> Rank 1 <small> / </small> <%= @projects.size %> </p>
			    </div>
			</a>
		<% end %>
		</div>
	</div>
</div>

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<div class="row">
	<h2>New Project</h2>
</div>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>

app/views/welcome/index.html.erb
    <div class="site-wrapper">

      <div class="site-wrapper-inner">

        <div class="cover-container">

          <div class="masthead clearfix">
            <div class="inner">
              <h3 class="masthead-brand">LAB<font color="red">49</font></h3>
              <ul class="nav masthead-nav">
                <li class="active"><a href="#">Home</a></li>
                <li><%= link_to 'Projects', projects_path %></li>
              </ul>
            </div>
          </div>

          <div class="inner cover">
            <h1 class="cover-heading">YUDH</h1>
            <p class="lead">Driving developer competitveness using Pi.</p>
            <p class="lead">
              <a href="#" class="btn btn-lg btn-default">Learn more</a>
            </p>
          </div>

          <div class="mastfoot">
            <div class="inner">
              <p> a <a href="http://getbootstrap.com">PITY</a> initiative, by <a href="https://twitter.com/mdo">LAB49</a>.</p>
            </div>
          </div>

        </div>

      </div>

    </div>